"""Add created_at column to user table

Revision ID: f221f4a8359d
Revises: fd9a1b2c3e4f
Create Date: 2025-10-24 21:58:18.135043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f221f4a8359d'
down_revision = 'fd9a1b2c3e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_data_log_date'), ['log_date'], unique=False)

    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_log_entry_log_date'), ['log_date'], unique=False)

    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('motto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('motto', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entry_log_date'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('daily_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_data_log_date'))

    # ### end Alembic commands ###
